[project]
name = "lecture-4-dmrg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.0",
    "matplotlib>=3.8.0",
    "numpy>=1.24.0",
    "opt-einsum>=3.3.0",
    "physics-tenpy>=1.1.0",
    "scipy>=1.11.0",
]
